"""
models/session.py
-----------------
SQLAlchemy 2.0 ORM model for the ``analysis_sessions`` table.

Design notes:
- UUID primary keys are stored as strings in SQLite (which has no native UUID
  type) but converted to/from Python ``uuid.UUID`` objects transparently.
- ``assumptions`` and ``counter_arguments`` are stored as JSON columns.
  SQLAlchemy's ``JSON`` type maps to SQLite's TEXT column and handles
  serialisation automatically.
- ``created_at`` defaults to the UTC moment of insertion via
  ``datetime.utcnow`` so timestamps are timezone-naive UTC (ISO-8601 format
  when serialised by Pydantic).
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database.database import Base


class AnalysisSession(Base):
    """
    Persisted record of a single ADVOCATE analysis run.

    Every successful call to ``POST /analyze`` produces one row in this table
    so users (and developers) can retrieve historical analyses.

    Columns
    -------
    session_id:
        UUID v4 string – primary key.  Generated by the application layer,
        not the database, so we never depend on database-side UUID generation.
    idea:
        The original idea text submitted by the user (up to ~64 KB in SQLite).
    mode:
        The analysis mode: "standard" | "quick" | "deep".
    score:
        Float 1.0–5.0 – the idea quality score from the Quality Assessor.
    quality_label:
        Human-readable label for the score bucket (e.g. "Poor", "Moderate").
    attack_intensity:
        Derived from score – "aggressive" | "balanced" | "surgical".
    assumptions:
        JSON array of assumption objects produced by the Assumption Scanner.
    counter_arguments:
        JSON array of counter-argument objects from the Steelman Generator.
    verdict:
        Long-form final judgement paragraph from the Formatter agent.
    summary:
        Short ≤ 3-sentence TL;DR.
    llm_provider:
        Records which LLM backend produced the output: "anthropic" | "openai"
        | "mock".
    processing_time_seconds:
        Wall-clock latency of the full pipeline in fractional seconds.
    created_at:
        UTC timestamp of row insertion.
    """

    __tablename__ = "analysis_sessions"

    # -----------------------------------------------------------------------
    # Primary key
    # -----------------------------------------------------------------------
    session_id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        comment="UUID v4 primary key, generated by the application.",
    )

    # -----------------------------------------------------------------------
    # User input
    # -----------------------------------------------------------------------
    idea: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="The original idea text submitted by the user.",
    )
    mode: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="standard",
        comment="Analysis mode: standard | quick | deep.",
    )

    # -----------------------------------------------------------------------
    # Quality Assessor outputs
    # -----------------------------------------------------------------------
    score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Idea quality score from 1.0 (very poor) to 5.0 (excellent).",
    )
    quality_label: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="Human-readable label for the score (e.g. 'Poor', 'Moderate').",
    )
    attack_intensity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="Derived attack mode: aggressive | balanced | surgical.",
    )

    # -----------------------------------------------------------------------
    # Agent outputs stored as JSON
    # -----------------------------------------------------------------------
    assumptions: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=list,
        comment="JSON array of AssumptionItem dicts from the Assumption Scanner.",
    )
    counter_arguments: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=list,
        comment="JSON array of CounterArgumentItem dicts from Steelman Generator.",
    )

    # -----------------------------------------------------------------------
    # Formatter outputs
    # -----------------------------------------------------------------------
    verdict: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Final verdict paragraph from the Formatter agent.",
    )
    summary: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Short TL;DR summary (≤ 3 sentences).",
    )

    # -----------------------------------------------------------------------
    # Metadata
    # -----------------------------------------------------------------------
    llm_provider: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="mock",
        comment="LLM provider used: anthropic | openai | mock.",
    )
    processing_time_seconds: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
        comment="Total pipeline latency in fractional seconds.",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        default=datetime.utcnow,
        comment="UTC timestamp of session creation.",
    )

    def __repr__(self) -> str:
        return (
            f"<AnalysisSession id={self.session_id!r} "
            f"score={self.score} intensity={self.attack_intensity!r}>"
        )
